-- Alter table public.ozon_products
ALTER TABLE public.ozon_products ADD COLUMN "0" TEXT;
ALTER TABLE public.ozon_products ADD COLUMN "1" TEXT;
ALTER TABLE public.ozon_products ADD COLUMN "2" TEXT;
ALTER TABLE public.ozon_products ADD COLUMN "3" TEXT;
ALTER TABLE public.ozon_products ADD COLUMN "4" NUMERIC(10,2);
ALTER TABLE public.ozon_products ADD COLUMN "5" BIGINT;
ALTER TABLE public.ozon_products ADD COLUMN "6" NUMERIC(10,2);
ALTER TABLE public.ozon_products ADD COLUMN "7" NUMERIC(10,2);
ALTER TABLE public.ozon_products ADD COLUMN "8" NUMERIC(10,2);
ALTER TABLE public.ozon_products ADD COLUMN "9" TEXT;
ALTER TABLE public.ozon_products ADD COLUMN "10" BIGINT;
ALTER TABLE public.ozon_products ADD COLUMN "11" BIGINT;
ALTER TABLE public.ozon_products ADD COLUMN "12" BIGINT;
ALTER TABLE public.ozon_products ADD COLUMN "13" BIGINT;
ALTER TABLE public.ozon_products ADD COLUMN "14" TEXT;
ALTER TABLE public.ozon_products ADD COLUMN "15" TEXT;
ALTER TABLE public.ozon_products ADD COLUMN "16" BOOLEAN;
ALTER TABLE public.ozon_products ADD COLUMN "17" BOOLEAN;